<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>


<div class="below-footer container">
    <div class="foot-links">
		<a href="#" class=" foot-link twitter fa fa-twitter"></a>
		<a class=" foot-link facebook fa fa-facebook" href="#"></a>
		<a class=" foot-link google fa fa-google-plus" href="#"></a>
		<a class=" foot-link instagram fa fa-instagram" href="#"></a>
		<a class=" foot-link pinterest fa fa-pinterest" href="#"></a>
        
    </div>
    <div class="foot-text font-Oswald">
        Copyright &copy; 2021-present Humcommerce, Inc. All rights reserved.
    </div>

</div>

