<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="footer">
<div class="my-news-letter flex-col items-center justify-center text-center pt-[140px] ">
        <img class="mx-auto" src="<?php echo $this->getViewFileUrl('images/newletter-icon.png'); ?>" alt ="plane icon" />
        <h2 class="2xl pt-5 font-bold tracking-[5px] text-[23px] font-Oswald pb-[10px]">GET 15% OFF BY SUBSCRIBING TO OUR NEWSLETTER</h2>
        <div class="pt-[50px]">
            <input name="email"
                type="email"
                required
                id="newsletter-subscribe"
                class="border-0 border-b border-black border-solid text-sm h-10 font-Oswald w-[350px] news-input"
                placeholder="<?= $escaper->escapeHtmlAttr(__('Your email address')) ?>">
            <button class=" ml-4 bg-black text-white w-[81px] h-[40px] uppercase news-button px-7 font-Oswald">
            <?= $escaper->escapeHtml(__('Send')) ?>
            </button>
        </div>
        


    </div>
<div class="below-footer container">
    <div class="foot-links">
		<a href="#" class=" foot-link twitter fa fa-twitter"></a>
		<a class=" foot-link facebook fa fa-facebook" href="#"></a>
		<a class=" foot-link google fa fa-google-plus" href="#"></a>
		<a class=" foot-link instagram fa fa-instagram" href="#"></a>
		<a class=" foot-link pinterest fa fa-pinterest" href="#"></a>
        
    </div>
    <div class="foot-text font-Oswald">
        Copyright &copy; 2021-present Humcommerce, Inc. All rights reserved.
    </div>

</div>
</div>
