<div class="my-news-letter flex-col items-center justify-center text-center mt-[100px] mb-[140px]">
        <img class="mx-auto" src="<?php echo $this->getViewFileUrl('images/newletter-icon.png'); ?>" alt ="plane icon" />
        <h2 class="2xl pt-5 font-bold tracking-wide text-[23px] font-oswald">GET 10% OFF BY SUBSCRIBING TO OUR NEWSLETTER</h2>
        <div class="pt-[50px]">
            <input name="email"
                type="email"
                required
                id="newsletter-subscribe"
                class="border-0 w-80 border-b border-black border-solid text-sm pl-4 h-10"
                placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your email address')) ?>">
            <button class=" ml-4 bg-black text-white h-10 px-7">
            <?= $escaper->escapeHtml(__('Send')) ?>
            </button>
        </div>
        


    </div>