<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit;
use Magento\Framework\Escaper;

/** @var Edit $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroicons */
$heroicons = $viewModels->require(HeroiconsSolid::class);
?>
<?php if ($block->isProductVisibleInSiteVisibility()): ?>
    <a class="action action-delete flex justify-center w-[84px] bg-[#5d5d5d]"
       href="<?= $escaper->escapeUrl($block->getConfigureUrl()) ?>"
       title="<?= $escaper->escapeHtmlAttr(__('Edit item parameters')) ?>"
    >
    <button class="btn text-[13px] rounded-none  w-[auto] bg-[#5d5d5d] font-sans uppercase font-bold py-[5px] w-auto pl-[34px] ">Edit</button>
        <span class="sr-only"><?= $escaper->escapeHtml(__('Edit')) ?></span>
    </a>
<?php endif ?>
