<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove;
use Magento\Framework\Escaper;

/** @var Remove $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var HeroiconsSolid $heroicons */
$heroicons = $viewModels->require(HeroiconsSolid::class);

?>
<a href="#"
   title="<?= $escaper->escapeHtml(__('Remove item')) ?>"
   class="action action-delete flex justify-center w-[151px] bg-[#5d5d5d]"
   x-data="{}"
   @click.prevent='hyva.postForm(<?= /* @noEscape */ $block->getDeletePostJson() ?>)'
>
    <button class="btn text-[13px] rounded-none  w-[auto] bg-[#5d5d5d] font-sans uppercase font-bold py-[5px] w-auto pl-[34px] ">Remove item</button>
    <span class="sr-only"><?= $escaper->escapeHtml(__('Remove item')) ?></span>
</a>
