<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength

/** @var Escaper $escaper */
/** @var Template $block */

$title = "This is the default Hyvä Theme.";
$link = "https://hyva.io/";
?>
<section class="text-gray-700 body-font flex relative z-10">
    <div class="container mx-auto flex px-5 mt-8 xl:-mt-12 md:flex-row flex-col items-center">
        
        
    </div>
</section>
