<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>

<div class="w-full">
    <div class="w-full lg:w-1/4 float-left lg:float-right lg:order-2 top-0 lg:sticky my-[24px] bg-[#f5f5f5] ">
        <div class="flex pb-3 my-2 border-b border-gray-300 flex-col">
            <h2 class="w-full text-[14px] uppercase text-center text-gray-900 title-font font-sans md:text-left opacity-[0.5] ">
                <?= $escaper->escapeHtml(__('Summary')) ?>
            </h2>
        </div>
        <?= $block->getChildHtml('cart.summary') ?>
    </div>
    <div class="w-full lg:w-3/4 float-left lg:order-1 lg:pr-8">
        <?= $block->getChildHtml('form_before') ?>
        <?= $block->getChildHtml('cart-items') ?>
        <?= $block->getChildHtml('checkout_cart_widget') ?>
    </div>
    <div class="w-full lg:w-3/4 lg:pr-8">
        <?= $block->getChildHtml('cart.discount') ?>
    </div>
</div>
