<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $viewModels->require(ProductAttributes::class);
/** @var Product $product */
$product = $productViewModel->getProduct();

?>
<div class="order-2 w-full mb-6 md:w-7/12 md:pl-5 lg:pl-5  md:py-6 lg:py-0 lg:w-1/2 md:mb-0">
    <p class="hidden md:block text-[18px] uppercase font-sans mb-3 md:text-[18px] text-gray-900 title-font tracking-[1px] ">
        <strong class="font-semibold md:font-bold"><?= $escaper->escapeHtml($product->getName()) ?></strong>
    </p>
    <div class=" w-[34px] h-[3px] bg-[#484747] mb-5 "></div>
    
    <div class="my-2 flex flex-col">
        <?= $block->getChildHtml('product.info.review') ?>
    </div>
    <div class=" text-extrabold text-[4px]">
        <?= $block->getChildHtml("product.info.price") ?>
    </div>
    
    <?php if ($shortDescription = $productViewModel->getShortDescription()) { ?>
        <div class="mb-4 leading-relaxed product-description prose"><?= /* @noEscape */ $shortDescription ?></div>
    <?php } ?>

    <div class="flex">
    <div class="flex flex-col sm:flex-row justify-between my-4">
        <?= $block->getChildHtml("product.info.stockstatus") ?>
        <?= $block->getChildHtml("alert.urls") ?>
    </div>

    <div id="product-details">
        <?php foreach ($block->getAttributes() as $attributeConfig) {
            $attribute = $attributesViewModel->getAttributeFromLayoutConfig($attributeConfig); ?>
            <?php if ($value = $attribute['value'] ?? null) { ?>
                <div class="flex whitespace-nowrap my-[16px] p-0 ml-5 items-center <?=/* @noEscape */
                                                                                          $attribute['value'] ?: "" ?>">
                    <span class="w-auto text-left text-black text-[14px] font-sans  product-detail-label">
                        <?= $escaper->escapeHtml($attribute['label']) ?>
                    </span>
                    <span class="w-1/2 ml-2 text-left text-[13px] text-[#5d5d5d] font-sans lowercase product-detail-value">
                        <?= $escaper->escapeHtml($value) ?>
                    </span>
                </div>
            <?php } ?>
        <?php } ?>
    </div>
    </div>

    <?= $block->getChildHtml('product.info.form') ?>

    <div class="flex flex-col sm:flex-row items-end my-4">


        <div class="flex mt-4  sm:mt-0">
            <?php if ($product->isSaleable()): ?>
                <?= $block->getChildHtml("product.info.quantity") ?>
                <?= $block->getChildHtml("product.info.addtocart") ?>
            <?php endif; ?>
        </div>

    </div>

    <?php if ($product->isSaleable()): ?>
        <div class="flex mt-4 justify-end">
            <?= $block->getChildHtml('addtocart.shortcut.buttons') ?>
        </div>
    <?php endif; ?>

    <div class="flex mt-4">
        <?= $block->getChildHtml('product.info.addtowishlist'); ?>
        <?= $block->getChildHtml('product.info.addtocompare'); ?>
        <?= $block->getChildHtml('product.info.emailtofriend'); ?>
        <?= $block->getChildHtml('product.info.additional.actions'); ?>
    </div>

    <?php if ($tierPriceBlock = $block->getChildHtml("product.price.tier")): ?>
        <div class="py-4 my-2 tier-price-container">
            <?= /** @noEscape */ $tierPriceBlock ?>
        </div>
    <?php endif; ?>

    <?= $block->getChildHtml("product.info.additional") ?>
</div>
